name: in_app_purchase_example
description: Demonstrates how to use the in_app_purchase plugin.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  in_app_purchase: ^3.0.7

  shared_preferences: ^2.0.0

  apphud:
    path: ./apphud

dev_dependencies:
  flutter_driver:
    sdk: flutter

  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
